openedx/openedx-webhooks

- openedx_webhooks/views/jira.py
@singingwolfboy Does that look right?
> Automatically transition Solutions tickets to open status for OpenCraft

- openedx_webhooks/oauth.py
- requirements.txt
It's just making the bot less reliable. @sarina, can you review this?
> Remove CacheControl

- openedx_webhooks/views/jira.py
> Transition OSPR subtasks to backlog state

- openedx_webhooks/views/jira.py
@singingwolfboy conditional loops omg
> Simplify logic for determining transition state

- openedx_webhooks/views/github.py
@singingwolfboy @sarina Simple change.
> Contributor's agreement moved.

- openedx_webhooks/info.py
- openedx_webhooks/utils.py
- openedx_webhooks/views/github.py
- openedx_webhooks/views/jira.py
http://docs.python-requests.org/en/latest/api/?highlight=raise_for_status#requests.Response.raise_for_status
> responses have a raise_for_status() method that is neat

- openedx_webhooks/templates/github_rescan.html
- openedx_webhooks/views/github.py
@singingwolfboy can you take a quick look please.
> Chunk the rescan repos job so it doesn't time out.

- .travis.yml
@singingwolfboy - this is related to a change Travis made.
See #32 where two builds were run (a pr build and a branch build)
> Change travis config to only build master branch

- docs/install.rst
- openedx_webhooks/__init__.py
- openedx_webhooks/github_views.py
- openedx_webhooks/jira_views.py
- openedx_webhooks/utils.py
- requirements.txt
> Use Sentry instead of Bugsnag

- openedx_webhooks/github_views.py
This should resolve the Sentry error we saw. @sarina @nedbat
> Pass auth to is_internal_pull_request

- .travis.yml
- dev-requirements.txt
- openedx_webhooks/github_views.py
- tests/conftest.py
- tests/test_pr_comments.py
> Stop duplicate contractor comments

- docs/install.rst
- openedx_webhooks/__init__.py
- openedx_webhooks/config.py
- openedx_webhooks/github_views.py
- openedx_webhooks/jira_views.py
- openedx_webhooks/oauth.py
- openedx_webhooks/tasks/__init__.py
- openedx_webhooks/tasks/github.py
- openedx_webhooks/templates/github_rescan.html
- openedx_webhooks/utils.py
- requirements.txt
- tests/test_pr_comments.py
Move GitHub tasks to a Celery worker
> Move GitHub tasks to Celery worker

- openedx_webhooks/jira_views.py
edX doesn't do anything with them anymore
> Remove clarice and bnotions

- tests/conftest.py
- tests/test_pr_comments.py
> Simplify test request context

- openedx_webhooks/github_views.py
> Correct variable name, and check contents

- openedx_webhooks/github_views.py
> Don't need to parse the JSON twice

- openedx_webhooks/templates/github_community_pr_comment.md.j2
> Add some more whitespace to bot comments

- openedx_webhooks/templates/github_community_pr_comment.md.j2
Hi @sarina, I suggest the following text for edx-webhook.
* Have I understood the process correctly?
* Is the text suitable?
> Clarify the AUTHORS file process.

- openedx_webhooks/tasks/github.py
Addressing this issue: https://app.getsentry.com/edx-1/openedx-webhooks/issues/102956884/
@nedbat and/or @jbarciauskas, can you review this?
> No Sentry error for deleted JIRA issue

- openedx_webhooks/tasks/__init__.py
- tests/conftest.py
> More mocking

- .gitignore
- openedx_webhooks/__init__.py
- setup.py
@cpennington, does this look good?
> Adding a setup.py file

- README.rst
We have make task, let's use make task
@edx/ospr
> Update documentation on how we run tests

- README.rst
Add instructions we have *so far* for development using the Heroku infrastructure.
/cc @edx/ospr
> Add Heroku instructions

- openedx_webhooks/tasks/utils.py
> Oops, `response` is an object, not dict

- README.rst
> Add step about pushing to staging

- openedx_webhooks/jira/tasks.py
To be in alignment with the final implementation in production JIRA.
/cc @edx/ospr
> Update JIRA GitHub activity field names

- openedx_webhooks/templates/github_contractor_pr_comment.md.j2
- tests/test_pr_comments.py
> Add `nofollow` attribute to create OSPR link

- openedx_webhooks/github/dispatcher/actions/new_pull_request.py
Convert new GitHub PR into OSPR if appropriate. Also make the right comments on the PR itself as needed.
> WIP: Rewrite handling of new GitHub PR

- openedx_webhooks/info.py
- tests/cassettes/tests.test_info.test_current_person.json
- tests/cassettes/tests.test_info.test_current_person_has_institution.json
- tests/cassettes/tests.test_info.test_current_person_no_institution.json
- tests/cassettes/tests.test_info.test_updated_person.json
- tests/cassettes/tests.test_info.test_updated_person_has_institution.json
- tests/cassettes/tests.test_info.test_updated_person_no_institution.json
- tests/repo_data/people.yaml
- tests/test_info.py
This should check the before entry in people.yaml to see if the PR was created while a former employee was at edX. 
Do we have data to test this in staging?
> adding check for former edX employee

- README.rst
Adding a note that former employees with stale PRs should no longer open OSPRs
> updating the readme

- openedx_webhooks/github_views.py
- openedx_webhooks/templates/github_rescan.html
This is undoubtedly a work in progress. I haven't added any new tests since nothing in the openedx_webhooks/github_views.py file has actually been tested. Do you think a new file in the test directory is needed?
> rescan all repos now uses the GH api

- openedx_webhooks/ui.py
- openedx_webhooks/utils.py
Based on:
http://flask.pocoo.org/snippets/8/
> Add HTTP basic auth to homepage.

- openedx.yaml
Repo: https://github.com/edx/openedx-webhooks
Link: https://open-edx-proposals.readthedocs.io/en/latest/oep-0002-bp-repo-metadata.html
> [PROD-1013] Update to OEP-2 compliance.

- changelog.d/20210830_160831_nedbat_simpler_jira_auth.rst
- openedx_webhooks/lib/jira/client.py
> build: no need for two private key settings

- Dockerfile
- Makefile
- openedx_webhooks/github/dispatcher/actions/test/test_github_cla.py
- openedx_webhooks/github/dispatcher/actions/utils.py
- openedx_webhooks/tasks/pr_tracking.py
- tests/fake_github.py
- tests/test_pull_request_opened.py
- tests/test_rescan.py
and then mark as passing once they have.
> feat: fail builds if contributor needs to sign a CLA, but hasn't

- openedx_webhooks/info.py
Add debug logging so that we can validate that we're fetching files from the
correct location when testing on staging.
> docs: Add debug logging when we fetch files.

- openedx_webhooks/info.py
Don't just cache the yaml file, cache any file we load from
the DATA_FILE_URL_BASE.
We also memoize the people file because that does some computation
that we don't want to have to keep doing over and over again to combine
the yaml and salesforce file.
> feat: Update how we cache data files we load.

- openedx_webhooks/github/models.py
- openedx_webhooks/github_views.py
- openedx_webhooks/tasks/pr_tracking.py
- openedx_webhooks/test_helpers/fixtures/webhooks_data.py
- setup.py
- tests/conftest.py
- tests/fake_github.py
I guess we don't use setup.py, since it had an extraneous parenthesis?!?
> style: fix mypy and pylint errors

- README.rst
- changelog.d/20220511_164555_nedbat.rst
- changelog.d/20220527_083654_nedbat_new_jira.rst
- changelog.d/20220527_091411_nedbat_new_jira.rst
- docs/install.rst
- openedx_webhooks/bot_comments.py
- openedx_webhooks/gh_projects.py
- openedx_webhooks/lib/jira/client.py
- openedx_webhooks/oauth.py
- openedx_webhooks/settings.py
- openedx_webhooks/tasks/pr_tracking.py
- openedx_webhooks/templates/github_blended_pr_comment.md.j2
- openedx_webhooks/templates/github_committer_pr_comment.md.j2
- openedx_webhooks/templates/github_community_pr_comment.md.j2
- openedx_webhooks/templates/github_community_pr_comment_closed.md.j2
- openedx_webhooks/types.py
- tests/conftest.py
- tests/fake_github.py
- tests/fake_jira.py
- tests/faker.py
- tests/helpers.py
- tests/test_fake_jira.py
- tests/test_gh_projects.py
- tests/test_helpers.py
- tests/test_pr_comments.py
- tests/test_pull_request_closed.py
- tests/test_pull_request_opened.py
- tests/test_rescan.py
- The JIRA server is now configurable
- External pull requests are added to a GitHub project
> Changes due to Atlassian split

- changelog.d/20220601_171348_nedbat_bd_project.rst
- docs/install.rst
- openedx_webhooks/settings.py
- openedx_webhooks/tasks/pr_tracking.py
- tests/conftest.py
- tests/test_pull_request_opened.py
Natalia would like to have Blended pull requests in a different project than non-blended.
> feat: GITHUB_BLENDED_PROJECT for blended pull requests

- changelog.d/20230810_063412_nedbat_no_jenkins.rst
- docs/details.rst
- openedx_webhooks/bot_comments.py
- openedx_webhooks/tasks/pr_tracking.py
- tests/test_pull_request_opened.py
This comment was only for Jenkins, which isn't the CI we use anymore.
> feat!: no longer comment 'jenkins ok to test'

- openedx_webhooks/bot_comments.py
- openedx_webhooks/cla_check.py
- openedx_webhooks/github_views.py
- openedx_webhooks/tasks/pr_tracking.py
- openedx_webhooks/utils.py
- tests/fake_github.py
- tests/fake_jira.py
> style: pylint and mypy fixes

- openedx_webhooks/github_views.py
- openedx_webhooks/templates/main.html
for testing the error reporting.
> feat: add a way to cause celery task errors #266

- openedx.yaml
Continuing maintainership updates for 2U 2024.
> chore: update supporting teams

- docs/index.rst
Ref: https://github.com/openedx/docs.openedx.org/issues/955
> docs: Update edx.rtd links to docs.openedx.org

- openedx_webhooks/tasks/pr_tracking.py
The merged_at data is in a `pull_request` sub dict in the webhook data.
> fix: `merged_at` is in a sub dictionary in webhook data.
