openedx_webhooks/github_views.py, openedx_webhooks/jira_views.py
Docs were initially unclear about client.context vs client.extra_context.
Turns out that arbitrary information that we don't expect Sentry to
do anything in particular with goes in extra_context().
=> Call sentry.client.extra_context()

openedx_webhooks/jira_views.py, openedx_webhooks/tasks/__init__.py, openedx_webhooks/tasks/github.py, openedx_webhooks/tasks/jira.py
Our load on the webservers is still very spiky, and it appears to be spiking once per hour. I'm betting it's because of the "rescan JIRA users" task which is run once every hour. Moving this to the task queue will smooth our the load on the webservers, which will hopefully make them more reliable.
=> Move JIRA rescan user task to task queue

openedx_webhooks/jira_views.py
@sarina: This should make the bot stop complaining about external pull requests. However, it relies on JIRA issues having the "repo" field filled out correctly. If the field is empty, or filled out incorrectly, then there's not really anything the bot can do but throw an error. I've corrected the "repo" field on [OSPR-850](https://openedx.atlassian.net/browse/OSPR-850).
=> Ignore external OSPR issues

openedx_webhooks/jira_views.py
In JIRA, you can name a state transition whatever you want -- the default name
is the name of the end state, but you can change that. It looks like the API
does expose the name of the end state, so we should key off of that, in case
the transition has a different name from the end state.
Note that this assumes that there will never be more than one transition ending
at the same state. If that happens, one of them will be clobbered. (It's not
clear that we have a good way of dealing with that even before this change.)
=> Use the name of the end state rather than the name of the transition

openedx_webhooks/templates/github_pr_cover_letter.md.j2
@nedbat @lamagnifica, I've added a bit of text for documentation in the base cover letter. How's this look?
=> Add some docs info to the internal PR cover letter.

openedx_webhooks/jira_views.py
For IT-534:
* Removed group auto-assignation for edx-employees and qualcomm.
* Updated group auto-assignation for ubc to partner-ubc until we discover the implications.
=> IT-534 - Removed and Changed Group Auto-Assignation Rules

Procfile, openedx_webhooks/config.py, openedx_webhooks/tasks/example.py, openedx_webhooks/tasks/github.py, openedx_webhooks/tasks/utils.py, tests/tasks/test_example.py
Add logging for Celery tasks which are used to handle GitHub PR open and close events.
Also:
* Make sure Heroku Celery worker task actually outputs logging statements
* Created an example Celery task to test logging and establish testing pattern
/cc @edx/ospr
=> Additional logging for GitHub PR web hook Celery tasks

requirements/base.in, requirements/base.txt, requirements/doc.txt, requirements/test.txt
Celery 4 is out and isn't compatible with our code.
/cc @edx/ospr
=> Lock down Celery version

openedx_webhooks/github/dispatcher/rules/github_activity.py, openedx_webhooks/github/models.py, openedx_webhooks/lib/edx_repo_tools_data/models.py, openedx_webhooks/lib/edx_repo_tools_data/test/models/conftest.py, openedx_webhooks/lib/edx_repo_tools_data/test/models/test_person.py, openedx_webhooks/lib/jira/models.py, openedx_webhooks/lib/jira/utils.py
1. Ignore incoming events from known bots (entries with `is_robot: true` in `people.yaml`).
2. For users not in `people.yaml` assume they are not edX users but still process the event.
/cc @edx/ospr
=> Handle robot and unknown person PR activities

openedx_webhooks/tasks/github.py, openedx_webhooks/templates/github_community_pr_comment.md.j2, tests/test_pr_comments.py
I simply removed the AUTHORS line from the template and then changed the tests to check that it didn't appear in any comments. The tests pass, but is that all that needs to be done?
=> Removing AUTHORS line from PR comments

openedx.yaml, openedx_webhooks/lib/edx_repo_tools_data/models.py, openedx_webhooks/lib/edx_repo_tools_data/test/models/test_person.py, openedx_webhooks/lib/github/test/utils/test_get_most_recent_hook.py, requirements/base.in, requirements/base.txt, requirements/constraints.txt, requirements/dev.txt, requirements/doc.in, requirements/pip-tools.txt, requirements/test.txt
Repo: https://github.com/edx/openedx-webhooks
OEP-18: https://open-edx-proposals.readthedocs.io/en/latest/oep-0018-bp-python-dependencies.html
Before merging run full test suite and ensure nothing is failing.
some code changes were made regarding the update of `arrow` package. The functionality to change current time based on days/months of `arrow` instance has changed and moved from the `replace()` function to the `shift()` function as visible in this example as well as code change:
```        
yesterday = arrow.now().replace(days=-1).date()
yesterday = arrow.now().shift(days=-1).date()
```
=> Update openedx-webhooks with oep-18.

LICENSE
Using [repo_health_dashboard](https://docs.google.com/spreadsheets/d/1VCxNVq-niT-uv5BFmsYPF21r6I2-IQ-GJbidF0zUPBc/edit#gid=921158295), we found that bunch of our public repositories did not have licenses.
It was determined all public repos should have a license. We did discovery on the repositories and determined which licenses were appropriate based on [confluence doc on licensing](https://openedx.atlassian.net/wiki/spaces/OPEN/pages/13959332/Licensing).
This PR adds the appropriate License.
You can find further info on this in the ticket [ARCHBOM-1618](https://openedx.atlassian.net/browse/ARCHBOM-1618)
=> [ARCHBOM-1618]: Adding apache License to this public repository

openedx_webhooks/info.py, tests/fake_github.py, tests/repo_data/people.yaml, tests/test_info.py
Add a new, optional field `branches` that gives core committers access to all branches that are specified in the set.
`branches` is a set of one or more specified branches that CCs have merge rights to.
`branches` can be a specific branch, such as `open-release/maple.1`, or a wildcard such as `open-release*`
This is dependent on https://github.com/edx/repo-tools-data-schema/pull/3
=> feat: Add branches field for core committers

Makefile, README.rst
Assuming the `README` was previously up-to-date and that I've sufficiently grokked it, this should offer a simplified interface for deploying with Heroku.
A stage deploy (from master) should be as simple as:
```sh
make deploy-stage
```
and prod:
```sh
make deploy-prod
```
You can also deploy from the current branch:
```sh
make deploy-stage-branch
```
or from an arbitrary branch:
```sh
make deploy-stage-branch DEPLOY_STAGING_COMMIT=feat/my-branch
```
Configuration/setup will be automatically run, if needed.
=> feat: simplify deployment steps and instructions

openedx_webhooks/tasks/pr_tracking.py, tests/test_pull_request_opened.py
This is part of a larger effort to ensure CLAs are signed pre-merge,
when needed.
It serves as a minimal first step, as well as providing an opportunity
for me (stvstnfrd) to familiarize myself with the Heroku workflow.
=> feat: add Github label to PR if CLA still needed

changelog.d/20210818_132501_nedbat_basic_auth_everywhere.rst, openedx_webhooks/github_views.py, openedx_webhooks/jira_views.py, openedx_webhooks/tasks/__init__.py, openedx_webhooks/templates/main.html
Also, use the correct GET view names in the HTML template, although the
POST view names worked also, since it was only getting the URL, which is
the same for both.
=> fix: protect all pages with basic auth

changelog.d/20211215_170624_nedbat_debug_openedx_fail.rst, changelog.d/20211216_174221_nedbat_debug_openedx_fail.rst, changelog.d/20211217_124844_nedbat_debug_openedx_fail.rst, openedx_webhooks/oauth.py, openedx_webhooks/tasks/github.py, openedx_webhooks/templates/github_community_pr_comment.md.j2, openedx_webhooks/utils.py, tests/conftest.py, tests/test_fake_github.py, tests/test_info.py
Also, improve the error handling to be sure we can see what's happening when an exception occurs.
=> Remove OAuth authentication for GitHub

openedx_webhooks/bot_comments.py, tests/fake_github.py, tests/test_pull_request_opened.py
@sarina Here's an approach to testing re-opening.
This points out two things:
First, the test fails because after closing and re-opening, the Jira ticket is still "Rejected."  I haven't looked into why that is.
Second, closing the PR adds a bot comment to take the survey.  Do we want to do anything about that? We could remove that comment, or we could add another "yay, re-opened!" comment, or something else.
=> test: add a failing test of reopen behavior

openedx_webhooks/github_views.py, openedx_webhooks/tasks/pr_tracking.py, tests/fake_github.py, tests/test_pull_request_opened.py
This makes the tests pass.  Since the "reopen" fact isn't in the pull request, but instead in the hook action, I added it to the pr data as a separate piece of information.
It's not great that the hook handler isn't tested by the test suite, and we have to add a line to the tests to parallel a line in the handler, but I think this will work.
@natabene is this the behavior you want?: When a pull request is reopened, the Jira status becomes "Community Manager Review", regardless of other considerations.
=> temp: map the action to a new key in the pr json, for reopening

changelog.d/20220324_222015_nedbat_better_reopen.rst, docs/details.rst, openedx_webhooks/bot_comments.py, openedx_webhooks/github_views.py, openedx_webhooks/tasks/pr_tracking.py, tests/fake_github.py, tests/test_fake_github.py, tests/test_pull_request_opened.py, tests/test_rescan.py
@sarina @natabene 
This is the full implementation of re-opening.  On re-opening, the bot deletes the "survey" comment that had been added, and the Jira ticket is returned to the state it was in when the pull request was closed.
=> Complete the re-open work

openedx_webhooks/info.py, tests/conftest.py
As a part of the transition from edX to tCRIL, the repo-tools-data repo did
not get transferred.  A copy of the data needed by this application was made
and put into the openedx-webhooks-data repo in the openedx org.
This change points the app to load data from that repo instead.  Operationally,
that repo has the credentials for the edx-webhooks GitHub user and so that user
has also been given access to the new openedx-webhooks-data repo.
=> feat: Point the openedx_webhooks bot to the new data repo.

changelog.d/20220406_145815_nedbat_read_all_labels.rst, openedx_webhooks/jira_views.py, openedx_webhooks/tasks/github_work.py, openedx_webhooks/tasks/pr_tracking.py, tests/fake_github.py
We weren't paginating the labels, so we only got 30.  In edx-platform,
"open edx community review" was the 31st label, so we thought it didn't
exist, so we wouldn't add the label when a Jira ticket was transitioned
to Open edX Community Review.
=> fix: re-label to any jira status

openedx_webhooks/__init__.py, openedx_webhooks/config.py
The newer version of SQLAlchemy dropped support for the `postgres://` URI
scheme.  Add code to handle the URIs that heroku provides.
See https://help.heroku.com/ZKNTJQSK/why-is-sqlalchemy-1-4-x-not-connecting-to-heroku-postgres
for more details.
temp: Add some logging.
=> fix: Be able to read heroku postgres URLs

changelog.d/20220609_151524_nedbat_no_jira.rst, openedx_webhooks/bot_comments.py, openedx_webhooks/info.py, openedx_webhooks/settings.py, openedx_webhooks/tasks/pr_tracking.py, openedx_webhooks/templates/github_blended_pr_comment.md.j2, openedx_webhooks/templates/github_committer_pr_comment.md.j2, openedx_webhooks/templates/github_community_pr_comment.md.j2, openedx_webhooks/templates/github_community_pr_comment_closed.md.j2, tests/conftest.py, tests/helpers.py, tests/test_pull_request_closed.py, tests/test_pull_request_opened.py, tests/test_rescan.py
This change makes it possible to disable accessing Jira, or to have pull requests opened when one Jira server is connected, and then be closed when a different Jira server is connected.
=> feat: Jira might be turned off, or change over time

openedx_webhooks/templates/github_community_pr_comment.md.j2
Give users a way to re-run CLA checks themselves, and give them a way to
escalate CLA issues themselves.
=> docs: Add more detail for when CLA Checks fail.

openedx_webhooks/templates/github_community_pr_comment.md.j2
Because of the trimming in the filters, we have to explicitly add a
newline to separet these two paragraphs.
=> docs: Fix the spacing.

openedx_webhooks/github/dispatcher/actions/utils.py
The commits api only gets 30 commits.  Up the default number of commits
we get to 100 in case someone has a long running branch.
Long term we should add paging to this endpoint but this should fix it
in most cases.  The function currently returns the full JSON payload so
we'll need to update the return signature if we want to start using
paging here.  This may impact callers so we defer that work for now.
=> fix: Get more commits by default.

openedx_webhooks/labels.py, tests/test_pull_request_opened.py
BREAKING CHANGE: All labels are considered ad-hoc and we don't
automatically remove any labels that might have been added manually.
=> feat!: Stop syncing labels between Jira and github.

openedx_webhooks/github/dispatcher/actions/utils.py
A 2U'er thought the old message meant she couldn't make a pull request.  This is more direct.
=> fix: make the private-repo message more direct, less alarming

changelog.d/20230302_152318_nedbat_no_more_internal.rst, openedx_webhooks/github/dispatcher/actions/utils.py, openedx_webhooks/tasks/pr_tracking.py, openedx_webhooks/templates/no_contributions.md.j2, tests/repo_data/openedx/openedx-webhooks-data/orgs.yaml, tests/repo_data/openedx/openedx-webhooks-data/salesforce-export.csv, tests/test_info.py, tests/test_pull_request_opened.py
- Remove code that checked obsolete `internal` setting
- Tweak the wording of cla check messages
=> feat: no longer read the obsolete `internal` setting in orgs.yaml

openedx_webhooks/jira_views.py
This is so we can test 2U Jira sending us events without them actually doing anything.
=> debug: make the Jira endpoints log then do nothing

openedx_webhooks/github_views.py
When a repo within the openedx org is configured to use merge queues, a CLA check response is requested for each PR in the queue. This check was never being run, leading to the PR being removed from the queue. This updates the hook to support the enqueued action type for PRs to ensure the check is run for PRs in the queue.
=> feat: support running CLA check in merge queues

openedx_webhooks/templates/github_community_pr_comment.md.j2
We're moving towards a single set of guidelines org-wide.
=> docs: Update the contributing guidelines link.

.gitignore, openedx_webhooks/github_views.py
In preparation for acting on comments, I've refactored the logic that picks apart webhook payloads.
This doesn't change any behavior (except perhaps what gets logged for things we don't care about), but I wanted get review incrementally.
=> refactor: dispatch to functions for different activity

openedx_webhooks/config.py, openedx_webhooks/lib/rq.py
This is in preparation of an upgrade of the Redis server in production.
In production we use a premium redis server but it's running a fairly
old version of redis(4.x).  Heroku is about to drop support and force us
to use redis 7.x instead.  Before we do that, we want to make sure that
the server won't have any issues connecting to redis over a TLS
connection.  So we want to test it in staging first.
Unfortunately, n the staging environment we use the heroku redis mini
product.  This product allows for connecting over either a TLS
connection or a non-tls connection and provides a second environment
variable (REDIS_TLS_URL) if you want to connect to redis over TLS.  When
we upgrade production it will not provide this URL and the REDIS_URL
value will be secure by default.
So to validate we …
=> feat: Use a TLS redis url if it's available.

openedx_webhooks/cla_check.py, openedx_webhooks/github/dispatcher/actions/github_activity.py, openedx_webhooks/tasks/jira_work.py, openedx_webhooks/tasks/pr_tracking.py, tests/fake_github.py, tests/test_pull_request_opened.py
One of the things slowing me down is my general distaste for the structure of the current code. I'm trying to be more aggressive about pulling it into a shape I like better.
=> refactor: move useful code out of github.dispatch.actions.utils

changelog.d/20230828_154558_nedbat_comment_to_check_cla.rst, openedx_webhooks/github_views.py
Ed asked for a simpler way to re-check the CLA than editing the title of the PR.  Now any comment on a PR will re-check the PR.  No special syntax needed.
=> feat: commenting on a PR triggers updates and re-checks.

changelog.d/20230912_175059_nedbat_cla_for_more_than_100_commits.rst, openedx_webhooks/cla_check.py, tests/fake_github.py
This can be simplified even further, since elsewhere we've already gotten the full data about the PR, so we have the head sha someplace. That will require a bit more changes, and this will work.
Fixes https://github.com/openedx/openedx-webhooks/issues/217
=> fix: cla check works even with more than 100 commits

openedx_webhooks/templates/github_community_pr_comment.md.j2
The bot now re-checks when any comment is made to the PR.  Title editing isn't required.
=> fix: instructions shouldn't mention editing the PR title

docs/details.rst, openedx_webhooks/bot_comments.py, openedx_webhooks/info.py, openedx_webhooks/tasks/jira_work.py, openedx_webhooks/tasks/pr_tracking.py, openedx_webhooks/templates/github_blended_pr_comment.md.j2, openedx_webhooks/templates/github_community_pr_comment.md.j2, openedx_webhooks/templates/github_community_pr_comment_closed.md.j2, tests/conftest.py, tests/fake_jira.py, tests/helpers.py, tests/test_fake_jira.py, tests/test_pr_comments.py, tests/test_pull_request_closed.py, tests/test_pull_request_opened.py, tests/test_rescan.py
I tried to remove code that we wouldn't need in the future.  Some basic Jira operation code is still here, but not called.  There is probably more code that can be deleted, but this was a lot already.
=> refactor!: no longer create Jira issues when pull requests are created

openedx_webhooks/tasks/pr_tracking.py, openedx_webhooks/templates/main.html, tests/test_pull_request_opened.py
Also, a little bit more ad-hoc exception testing.
=> Improved exception handling

changelog.d/20231114_044217_nedbat.rst, openedx_webhooks/github_views.py
This check (that the comment create date and the pull request closed date are the same) might not be 100% fool-proof. If they are off by one second, the bot will still comment twice, but that should be unlikely.
=> fix: don't comment twice when a pr is closed with comment. #277

openedx_webhooks/tasks/pr_tracking.py
Per discussion in standup, let's disable this for now until we have a better story around looking at the data and only posting on first-timers PRs
=> feat! Turn off survey link for merged/closed PRs

tests/test_pull_request_closed.py, tests/test_rescan.py
I missed these when I force-merged https://github.com/openedx/openedx-webhooks/pull/299
=> test: update tests now that we don't post the survey link

openedx_webhooks/templates/no_contributions.md.j2
Ned isn't working at 2U anymore, so we should not be bothering him!
I'm not replacing this with better contact info, as it's not clear who that would be—or whether we even want this no-contributions behavior at all. So in the meantime, just removing incorrect info.
=> feat: Don't ping Ned

openedx_webhooks/templates/github_community_pr_comment.md.j2, tests/test_pull_request_opened.py
The current community message is quite long and key information is hard to
access at a glance. This condenses the message by collapsing sections that have
verbose information and putting key information at the start of the message.
=> feat: Update the community PR message to have collapsible sections

openedx_webhooks/templates/github_community_pr_comment.md.j2
This PR makes slight adjustments to the language that make it work better and sounds less repetitive after the recent changes to the structure of the message.
=> fix: Update community PR comment message slightly to remove duplication

openedx_webhooks/labels.py, openedx_webhooks/tasks/pr_tracking.py, openedx_webhooks/utils.py, tests/fake_github.py, tests/test_pull_request_closed.py
Removes obsolete labels from pull requests when it is merged or closed.
Related to: https://github.com/openedx/wg-coordination/issues/150
`Private-ref`: [FAL-4026](https://tasks.opencraft.com/browse/FAL-4026)
**Test instructions:**
* Set `GITHUB_PERSONAL_TOKEN=<your_token>` and `GITHUB_OSPR_PROJECT="openedx:19"` environment variables.
* Select a closed PR to test, you can use my [PR](https://github.com/openedx/openedx-webhooks/pull/327)
* Add some labels to PR like: `blocked by other work`, `needs reviewer assigned` etc.
* Get PR json using github cli, for example,
```sh
gh api \
-H "Accept: application/vnd.github+json" \
-H "X-GitHub-Api-Version: 2022-11-28" \
/repos/openedx/openedx-webhooks/pulls/327 > /tmp/some.json
```
* Update following lines in …
=> feat: remove obsolete labels on pr close

openedx_webhooks/templates/github_community_pr_comment.md.j2, tests/test_pull_request_opened.py
We had backticks before and we removed them when we re-worded this.
However, we should put them back in.  Currently the maintainers get
mentioned and there fore start recieving notifications on all PRs
whether or not they are ready for their review.  This is causing a bit
of churn and waste as people have to check more PRs than necessary
especially since many PRs have known reviewers from the same team or via
FCs.
=> fix: Don't mention the owner directly in the welcome message.

openedx_webhooks/templates/github_community_pr_comment.md.j2
The current message is too spaced out, this change fixes the spacing issues and moves the hr to the correct place.
The h3 and h4 have been removed since they add too much spacing around in the collapsable and make the message seem too spaced out. Being inside a collapsable section already highlights them quite a bit so I'm hoping this is okay. 
Screenshot after update:
=> refactor: Change the formatting of the community PR message to make it tighter

openedx_webhooks/info.py, tests/repo_data/openedx/openedx-webhooks-data/salesforce-export.csv
Github treats them in a case insensitive manner but users can still
choose the casing of their name.  Our code for looking up users
previously was case-sensitive which was causing failures when someone
changed the casing in their github username.
This change updates the code so that the name we get associated with a
PR and the name we look up in the salesforce exports are both lowercased
before we do any comparisons.
=> fix: Treat github usernames in a case-insensitively

openedx_webhooks/gh_projects.py, openedx_webhooks/tasks/pr_tracking.py, openedx_webhooks/types.py, tests/fake_github.py, tests/test_gh_projects.py, tests/test_pull_request_closed.py, tests/test_pull_request_opened.py, tests/test_rescan.py
Automatically adds closed/merged date to project item for a PR on close/merge.
* Set `GITHUB_PERSONAL_TOKEN=<your_token>` and `GITHUB_OSPR_PROJECT="openedx:19"` environment variables.
* Select a closed PR to test and make sure it has no value in `Date merged/closed` field in OSPR project board, you can use my [PR](https://github.com/openedx/edx-platform/pull/35899)
* Get PR json using github cli, for example,
```sh
gh api \
-H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" \
/repos/openedx/edx-platform/pulls/35899 > /tmp/some.json
```
* Update following lines in `openedx_webhooks/tasks/pr_tracking.py` to make the process faster.
```diff
Line 217 in `desired_support_state` function.
-    is_internal = is_internal_pull_request(pr)
+    is_internal = False
``` …
=> feat: automatically fill closed or merged date in project

openedx_webhooks/info.py, openedx_webhooks/labels.py, openedx_webhooks/tasks/pr_tracking.py, tests/test_info.py, tests/test_pull_request_opened.py
Implements https://github.com/openedx/wg-coordination/issues/155 adding a "core contributor" labels to all OSPRs.
=> feat: Add "core contributor" label to PRs by core contributors

openedx_webhooks/labels.py, tests/test_pull_request_opened.py
The previous implementation entirely automated the addition and removal of the "core contributor" label. Unfortunately this meant that adding the label manually to a PR didn't work since the webhook would run and remove the label if it didn't have the information to know that it would apply.
Fixes: https://github.com/openedx/wg-coordination/issues/159
=> fix: Don't remove "core contributor" label if manually added.
